---
abstract: "uploading files to a Google Code project.\r"
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.790'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Google-Code-Upload
no_index:
  directory:
    - inc
    - t
requires:
  File::Basename: 0
  File::Spec: 0
  Getopt::Long: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  MIME::Base64: 0
  Pod::Usage: 0
  Term::ReadKey: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
